FROM python:3.14

WORKDIR /src

COPY ./payment_service/requirements.txt /src/requirements.txt
RUN pip install --no-cache-dir --upgrade pip \
&& pip install --no-cache-dir -r /src/requirements.txt

COPY ./payment_service /src/payment_service
COPY .env /src/payment_service

EXPOSE 8002

CMD ["python", "payment_service/main.py"]