services:
    postgres:
        image: postgres:18
        container_name: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: learning
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql
            - ./auth_service/datasets:/datasets
    auth_service:
        build:
            context: .
            dockerfile: ./auth_service/dockerfile
        container_name: auth_service
        env_file:
            - .env
        ports:
            - "8000:8000"
    store_service:
        build:
            context: .
            dockerfile: ./store_service/dockerfile
        container_name: store_service
        env_file:
            - .env
        ports:
            - "8001:8001"
    payment_service:
        build:
            context: .
            dockerfile: ./payment_service/dockerfile
        container_name: payment_service
        env_file:
            - .env
        ports:
            - "8002:8002"
volumes:
    pgdata:
        