# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: store_service/protobuf/payment_service.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'store_service/protobuf/payment_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,store_service/protobuf/payment_service.proto\"0\n\x0ePaymentRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\r\n\x05\x61ppid\x18\x02 \x01(\t\"B\n\x0fPaymentResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x1e\n\x06status\x18\x02 \x01(\x0e\x32\x0e.PaymentStatus*\x84\x01\n\rPaymentStatus\x12\x1e\n\x1aPAYMENT_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n\x16PAYMENT_STATUS_PENDING\x10\x01\x12\x1c\n\x18PAYMENT_STATUS_SUCCEEDED\x10\x02\x12\x19\n\x15PAYMENT_STATUS_FAILED\x10\x03\x32\x42\n\x0ePaymentService\x12\x30\n\x0bMakePayment\x12\x0f.PaymentRequest\x1a\x10.PaymentResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'store_service.protobuf.payment_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PAYMENTSTATUS']._serialized_start=167
  _globals['_PAYMENTSTATUS']._serialized_end=299
  _globals['_PAYMENTREQUEST']._serialized_start=48
  _globals['_PAYMENTREQUEST']._serialized_end=96
  _globals['_PAYMENTRESPONSE']._serialized_start=98
  _globals['_PAYMENTRESPONSE']._serialized_end=164
  _globals['_PAYMENTSERVICE']._serialized_start=301
  _globals['_PAYMENTSERVICE']._serialized_end=367
# @@protoc_insertion_point(module_scope)
