FROM python:3.14

WORKDIR /src

COPY requirements.txt /src/requirements.txt
RUN pip install --no-cache-dir --upgrade pip \
&& pip install --no-cache-dir -r /src/requirements.txt

COPY ./auth_service /src/auth_service

EXPOSE 8000

CMD ["fastapi", "run", "auth_service/main.py", "--port", "8000"]