from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy import (
    Table,
    ARRAY,
    Column,
    Integer,
    Numeric,
    BigInteger,
    DateTime,
    Identity,
    Text,
    JSON,
    Boolean,
)

from store_service.engine import metadata_obj

games = Table(
    "games",
    metadata_obj,
    Column("appid", BigInteger, Identity(), primary_key=True),
    Column("name", Text, nullable=False),
    Column("release_date", DateTime, nullable=False),
    Column("required_age", Integer, nullable=False),
    Column("price", Numeric(10, 2), nullable=False),
    Column("packages", JSONB),
    Column("discount", Integer, nullable=False),
    Column("dlc_count", Integer, nullable=False),
    Column("detailed_description", Text),
    Column("about_the_game", Text),
    Column("short_description", Text),
    Column("reviews", Text),
    Column("header_image", Text),
    Column("website", Text),
    Column("support_url", Text),
    Column("support_email", Text),
    Column("windows", Boolean),
    Column("mac", Boolean),
    Column("linux", Boolean),
    Column("metacritic_score", Integer),
    Column("metacritic_url", Text),
    Column("achievements", Integer, nullable=False),
    Column("recommendations", Integer),
    Column("notes", Text),
    Column("supported_languages", JSONB),
    Column("full_audio_languages", JSONB),
    Column("developers", JSONB, nullable=False),
    Column("publishers", JSONB),
    Column("categories", JSONB),
    Column("genres", JSONB),
    Column("tags", JSONB),
    Column("screenshots", JSONB),
    Column("movies", JSONB),
    Column("positive", Integer),
    Column("negative", Integer),
)
