"""Initial store tables

Revision ID: 515f47614b3d
Revises: 
Create Date: 2026-07-31 16:31:24.938211

"""
from typing import Sequence, Union
import pandas as pd
import os

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '515f47614b3d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store_games',
    sa.Column('appid', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('release_date', sa.DateTime(), nullable=False),
    sa.Column('required_age', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount', sa.Integer(), nullable=False),
    sa.Column('dlc_count', sa.Integer(), nullable=False),
    sa.Column('detailed_description', sa.Text(), nullable=True),
    sa.Column('about_the_game', sa.Text(), nullable=True),
    sa.Column('short_description', sa.Text(), nullable=True),
    sa.Column('reviews', sa.Text(), nullable=True),
    sa.Column('header_image', sa.Text(), nullable=True),
    sa.Column('website', sa.Text(), nullable=True),
    sa.Column('support_url', sa.Text(), nullable=True),
    sa.Column('support_email', sa.Text(), nullable=True),
    sa.Column('windows', sa.Boolean(), nullable=True),
    sa.Column('mac', sa.Boolean(), nullable=True),
    sa.Column('linux', sa.Boolean(), nullable=True),
    sa.Column('metacritic_score', sa.Integer(), nullable=True),
    sa.Column('metacritic_url', sa.Text(), nullable=True),
    sa.Column('achievements', sa.Integer(), nullable=False),
    sa.Column('recommendations', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('positive', sa.Integer(), nullable=True),
    sa.Column('negative', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('appid')
    )
    op.create_table('store_categories',
    sa.Column('appid', sa.BigInteger(), nullable=False),
    sa.Column('categories', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['appid'], ['store_games.appid'], ),
    sa.PrimaryKeyConstraint('appid', 'categories')
    )
    op.create_table('store_developers',
    sa.Column('appid', sa.BigInteger(), nullable=False),
    sa.Column('developers', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['appid'], ['store_games.appid'], ),
    sa.PrimaryKeyConstraint('appid', 'developers')
    )
    op.create_table('store_game_audio_languages',
    sa.Column('appid', sa.BigInteger(), nullable=False),
    sa.Column('language', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['appid'], ['store_games.appid'], ),
    sa.PrimaryKeyConstraint('appid', 'language')
    )
    op.create_table('store_game_text_languages',
    sa.Column('appid', sa.BigInteger(), nullable=False),
    sa.Column('language', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['appid'], ['store_games.appid'], ),
    sa.PrimaryKeyConstraint('appid', 'language')
    )
    op.create_table('store_genres',
    sa.Column('appid', sa.BigInteger(), nullable=False),
    sa.Column('genres', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['appid'], ['store_games.appid'], ),
    sa.PrimaryKeyConstraint('appid', 'genres')
    )
    op.create_table('store_movies',
    sa.Column('appid', sa.BigInteger(), nullable=False),
    sa.Column('movies', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['appid'], ['store_games.appid'], ),
    sa.PrimaryKeyConstraint('appid', 'movies')
    )
    op.create_table('store_publishers',
    sa.Column('appid', sa.BigInteger(), nullable=False),
    sa.Column('publishers', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['appid'], ['store_games.appid'], ),
    sa.PrimaryKeyConstraint('appid', 'publishers')
    )
    op.create_table('store_screenshots',
    sa.Column('appid', sa.BigInteger(), nullable=False),
    sa.Column('screenshots', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['appid'], ['store_games.appid'], ),
    sa.PrimaryKeyConstraint('appid', 'screenshots')
    )
    op.create_table('store_tags',
    sa.Column('appid', sa.BigInteger(), nullable=False),
    sa.Column('tags', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['appid'], ['store_games.appid'], ),
    sa.PrimaryKeyConstraint('appid', 'tags')
    )

    path = "datasets"
    if os.path.isdir(path) and os.listdir(path):
        # load datasets
        bind = op.get_bind()
        #games table
        df = pd.read_csv("datasets/games_filtered.csv")
        df["release_date"] = pd.to_datetime(df["release_date"])
        df.to_sql("store_games", bind, if_exists="append", index=False)

        # other tables
        to_convert_columns = [
            "supported_languages",
            "full_audio_languages",
            "developers",
            "publishers",
            "categories",
            "genres",
            "screenshots",
            "movies",
            "tags",
        ]
        for col in to_convert_columns:
            df = pd.read_csv(f"datasets/{col}.csv")
            df.dropna(subset=[col], inplace=True)
            df.drop_duplicates(inplace=True)
            df.to_sql(f"store_{col}", bind, if_exists="append", index=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('store_tags')
    op.drop_table('store_screenshots')
    op.drop_table('store_publishers')
    op.drop_table('store_movies')
    op.drop_table('store_genres')
    op.drop_table('store_game_text_languages')
    op.drop_table('store_game_audio_languages')
    op.drop_table('store_developers')
    op.drop_table('store_categories')
    op.drop_table('store_games')
    # ### end Alembic commands ###
