FROM python:3.14

WORKDIR /src

COPY ./users_service/requirements.txt /src/requirements.txt
RUN pip install --no-cache-dir --upgrade pip \
&& pip install --no-cache-dir -r /src/requirements.txt

COPY ./users_service /src/users_service
COPY .env /src/users_service

# installs protos
COPY ./shared/protobufs /src/protobufs
WORKDIR /src/protobufs
RUN rm -rf ./src/*.egg-info ./build .eggs \
    && python -m pip install --no-cache-dir .

RUN python -m pip install .
WORKDIR /src

EXPOSE 8002

CMD ["python", "users_service/main.py"]