global:
  scrape_interval: 15s

scrape_configs:
  - job_name: auth_service
    metrics_path: /metrics
    static_configs:
      - targets:
        - auth_service:8000
  - job_name: store_service
    metrics_path: /metrics
    static_configs:
      - targets:
        - store_service:8001