"""init users_game_ownership table

Revision ID: 7229525d3431
Revises: 
Create Date: 2026-08-01 15:21:35.218407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7229525d3431'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_game_ownership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appid', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['appid'], ['store_games.appid'], ),
    sa.ForeignKeyConstraint(['id'], ['auth_users.id'], ),
    sa.PrimaryKeyConstraint('id', 'appid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_game_ownership')
    # ### end Alembic commands ###
