"""change id to username in users_game_ownership

Revision ID: 9175dde3d3c8
Revises: 7229525d3431
Create Date: 2026-08-01 18:25:25.510659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9175dde3d3c8'
down_revision: Union[str, Sequence[str], None] = '7229525d3431'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_game_ownership', sa.Column('username', sa.Text(), nullable=False))
    op.drop_constraint(op.f('users_game_ownership_id_fkey'), 'users_game_ownership', type_='foreignkey')
    op.create_foreign_key(None, 'users_game_ownership', 'auth_users', ['username'], ['username'])
    op.drop_column('users_game_ownership', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_game_ownership', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users_game_ownership', type_='foreignkey')
    op.create_foreign_key(op.f('users_game_ownership_id_fkey'), 'users_game_ownership', 'auth_users', ['id'], ['id'])
    op.drop_column('users_game_ownership', 'username')
    # ### end Alembic commands ###
