syntax = "proto3";

import "google/protobuf/struct.proto";

enum PaymentStatus {
  PAYMENT_STATUS_UNSPECIFIED = 0;
  PAYMENT_STATUS_PENDING = 1;
  PAYMENT_STATUS_SUCCEEDED = 2;
  PAYMENT_STATUS_FAILED = 3;
}

message MakePaymentRequest {
  string username = 1;
  int64 appid = 2;
  string price = 3;
}

message MakePaymentResponse {
  string payment_id = 1;
  string confirmation_url = 2;
}

message PaymentNotificationRequest {
  string type = 1;
  string event = 2;
  google.protobuf.Struct object = 3;
}

message PaymentNotificationResponse {
  PaymentStatus status = 1;
}

service PaymentService {
  rpc MakePayment(MakePaymentRequest) returns (MakePaymentResponse);
  rpc PaymentNotification(PaymentNotificationRequest) returns (PaymentNotificationResponse);
}
