"""added email column and changed prev

Revision ID: 5efbf92fe33c
Revises: 9363f5e49dff
Create Date: 2026-07-31 19:10:07.544647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5efbf92fe33c'
down_revision: Union[str, Sequence[str], None] = '9363f5e49dff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_users', sa.Column('email', sa.Text(), nullable=False))
    op.alter_column('auth_users', 'username',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('auth_users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.create_unique_constraint(None, 'auth_users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'auth_users', type_='unique')
    op.alter_column('auth_users', 'hashed_password',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('auth_users', 'username',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.drop_column('auth_users', 'email')
    # ### end Alembic commands ###
