# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: store_service/protobuf/users/users_service.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'store_service/protobuf/users/users_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0store_service/protobuf/users/users_service.proto\x12\x08users.v1\"7\n\x14\x41\x64\x64GameToUserRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\r\n\x05\x61ppid\x18\x02 \x01(\x03\"&\n\x15\x41\x64\x64GameToUserResponse\x12\r\n\x05\x61ppid\x18\x01 \x01(\x03\"1\n\x0eHasGameRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\r\n\x05\x61ppid\x18\x02 \x01(\x03\"!\n\x0fHasGameResponse\x12\x0e\n\x06result\x18\x01 \x01(\x08\x32\x9f\x01\n\x0bUserService\x12>\n\x07HasGame\x12\x18.users.v1.HasGameRequest\x1a\x19.users.v1.HasGameResponse\x12P\n\rAddGameToUser\x12\x1e.users.v1.AddGameToUserRequest\x1a\x1f.users.v1.AddGameToUserResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'store_service.protobuf.users.users_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ADDGAMETOUSERREQUEST']._serialized_start=62
  _globals['_ADDGAMETOUSERREQUEST']._serialized_end=117
  _globals['_ADDGAMETOUSERRESPONSE']._serialized_start=119
  _globals['_ADDGAMETOUSERRESPONSE']._serialized_end=157
  _globals['_HASGAMEREQUEST']._serialized_start=159
  _globals['_HASGAMEREQUEST']._serialized_end=208
  _globals['_HASGAMERESPONSE']._serialized_start=210
  _globals['_HASGAMERESPONSE']._serialized_end=243
  _globals['_USERSERVICE']._serialized_start=246
  _globals['_USERSERVICE']._serialized_end=405
# @@protoc_insertion_point(module_scope)
